development:
  adapter: mysql2
  #encoding: utf8
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: false
  database: doctors_app
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  #encoding: utf8
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: false
  database: doctors_app
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  #encoding: utf8
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: false
  database: doctors_app
  pool: 5
  username: root
  socket: /var/run/mysqld/mysqld.sock
  password:
